const artData =  {
    "objectID": 3,
    "isHighlight": false,
    "accessionNumber": "23.80.15",
    "accessionYear": "1923",
    "isPublicDomain": true,
    "primaryImageSmall": "https://images.metmuseum.org/CRDImages/ad/web-large/52601.jpg",
    "additionalImages": [],
    "constituents": null,
    "department": "The American Wing",
    "objectName": "Andiron",
    "title": "Andiron",
    "culture": "American",
    "period": "",
    "dynasty": "",
    "reign": "",
    "portfolio": "",
    "artistRole": "",
    "artistPrefix": "",
    "artistDisplayName": "",
    "artistDisplayBio": "",
    "artistSuffix": "",
    "artistAlphaSort": "",
    "artistNationality": "",
    "artistBeginDate": "",
    "artistEndDate": "",
    "artistGender": "",
    "artistWikidata_URL": "",
    "artistULAN_URL": "",
    "objectDate": "1795–1810",
    "objectBeginDate": 1795,
    "objectEndDate": 1810,
    "medium": "Brass, iron",
    "dimensions": "25 1/4 x 21 1/2 x 13 1/2 in. (64.1 x 54.6 x 34.3 cm)",
    "measurements": [
        {
            "elementName": "Overall",
            "elementDescription": null,
            "elementMeasurements": {
                "Depth": 34.3,
                "Height": 64.1,
                "Width": 54.6101
            }
        }
    ],
    "creditLine": "Gift of Mr. and Mrs. William A. Moore, 1923",
    "geographyType": "Made in",
    "city": "New York",
    "state": "New York",
    "county": "",
    "country": "United States",
    "region": "Mid-Atlantic",
    "subregion": "",
    "locale": "",
    "locus": "",
    "excavation": "",
    "river": "",
    "classification": "",
    "rightsAndReproduction": "",
    "linkResource": "",
    "metadataDate": "2023-02-07T04:46:51.34Z",
    "repository": "Metropolitan Museum of Art, New York, NY",
    "objectURL": "https://www.metmuseum.org/art/collection/search/65",
    "tags": null,
    "objectWikidata_URL": "https://www.wikidata.org/wiki/Q116373709",
    "isTimelineWork": false,
    "GalleryNumber": "728"
  }

// {
//     "objectID": 1,
//   "isHighlight": false,
//   "accessionNumber": "1979.486.3",
//   "accessionYear": "1979",
//   "isPublicDomain": false,
//   "primaryImage": "",
//   "primaryImageSmall": "",
//   "additionalImages": [],
//   "constituents": [
//       {
//           "constituentID": 1080,
//           "role": "Maker",
//           "name": "Bela Lyon Pratt",
//           "constituentULAN_URL": "http://vocab.getty.edu/page/ulan/500095555",
//           "constituentWikidata_URL": "https://www.wikidata.org/wiki/Q4881787",
//           "gender": ""
//       }
//   ],
//   "department": "The American Wing",
//   "objectName": "Coin",
//   "title": "Two-and-a-half-dollar Indian Head Coin",
//   "culture": "",
//   "period": "",
//   "dynasty": "",
//   "reign": "",
//   "portfolio": "",
//   "artistRole": "Maker",
//   "artistPrefix": "",
//   "artistDisplayName": "Bela Lyon Pratt",
//   "artistDisplayBio": "1867–1917",
//   "artistSuffix": "",
//   "artistAlphaSort": "Pratt, Bela Lyon",
//   "artistNationality": "American",
//   "artistBeginDate": "1867",
//   "artistEndDate": "1917",
//   "artistGender": "",
//   "artistWikidata_URL": "https://www.wikidata.org/wiki/Q4881787",
//   "artistULAN_URL": "http://vocab.getty.edu/page/ulan/500095555",
//   "objectDate": "1912",
//   "objectBeginDate": 1912,
//   "objectEndDate": 1912,
//   "medium": "Gold",
//   "dimensions": "Dimensions unavailable",
//   "measurements": [
//       {
//           "elementName": "Other",
//           "elementDescription": "Object diameter",
//           "elementMeasurements": {
//               "Diameter": 1.7
//           }
//       }
//   ],
//   "creditLine": "Gift of Heinz L. Stoppelmann, 1979",
//   "geographyType": "",
//   "city": "",
//   "state": "",
//   "county": "",
//   "country": "",
//   "region": "",
//   "subregion": "",
//   "locale": "",
//   "locus": "",
//   "excavation": "",
//   "river": "",
//   "classification": "",
//   "rightsAndReproduction": "",
//   "linkResource": "",
//   "metadataDate": "2021-04-06T04:41:04.967Z",
//   "repository": "Metropolitan Museum of Art, New York, NY",
//   "objectURL": "https://www.metmuseum.org/art/collection/search/10",
//   "tags": null,
//   "objectWikidata_URL": "",
//   "isTimelineWork": false,
//   "GalleryNumber": ""
//   },


// {
//   "objectID": 989,
//   "isHighlight": false,
//   "accessionNumber": "10.149.88",
//   "accessionYear": "1910",
//   "isPublicDomain": true,
//   "primaryImage": "https://images.metmuseum.org/CRDImages/ad/original/DP258638.jpg",
//   "primaryImageSmall": "https://images.metmuseum.org/CRDImages/ad/web-large/DP258638.jpg",
//   "additionalImages": [],
//   "constituents": null,
//   "department": "The American Wing",
//   "objectName": "Bread plate",
//   "title": "Bread Plate",
//   "culture": "Chinese, for American market",
//   "period": "",
//   "dynasty": "",
//   "reign": "",
//   "portfolio": "",
//   "artistRole": "",
//   "artistPrefix": "",
//   "artistDisplayName": "",
//   "artistDisplayBio": "",
//   "artistSuffix": "",
//   "artistAlphaSort": "",
//   "artistNationality": "",
//   "artistBeginDate": "",
//   "artistEndDate": "",
//   "artistGender": "",
//   "artistWikidata_URL": "",
//   "artistULAN_URL": "",
//   "objectDate": "1785–90",
//   "objectBeginDate": 1785,
//   "objectEndDate": 1790,
//   "medium": "Porcelain",
//   "dimensions": "Diam. 6 1/4 in. (15.9 cm)",
//   "measurements": [
//       {
//           "elementName": "Other",
//           "elementDescription": "Object diameter",
//           "elementMeasurements": {
//               "Diameter": 15.9
//           }
//       }
//   ],
//   "creditLine": "Bequest of James T. Woodward, 1910",
//   "geographyType": "Made in",
//   "city": "",
//   "state": "",
//   "county": "",
//   "country": "China",
//   "region": "",
//   "subregion": "",
//   "locale": "",
//   "locus": "",
//   "excavation": "",
//   "river": "",
//   "classification": "",
//   "rightsAndReproduction": "",
//   "linkResource": "",
//   "metadataDate": "2023-02-07T04:46:51.34Z",
//   "repository": "Metropolitan Museum of Art, New York, NY",
//   "objectURL": "https://www.metmuseum.org/art/collection/search/989",
//   "tags": [
//       {
//           "term": "Birds",
//           "AAT_URL": "http://vocab.getty.edu/page/aat/300266506",
//           "Wikidata_URL": "https://www.wikidata.org/wiki/Q5113"
//       },
//       {
//           "term": "Flowers",
//           "AAT_URL": "http://vocab.getty.edu/page/aat/300132399",
//           "Wikidata_URL": "https://www.wikidata.org/wiki/Q506"
//       },
//       {
//           "term": "Coat of Arms",
//           "AAT_URL": "http://vocab.getty.edu/page/aat/300126352",
//           "Wikidata_URL": "https://www.wikidata.org/wiki/Q14659"
//       }
//   ],
//   "objectWikidata_URL": "https://www.wikidata.org/wiki/Q116372670",
//   "isTimelineWork": false,
//   "GalleryNumber": "774"
// }

export default artData